### ISSUE TITLE
Add Rna-transciption

### ISSUE THREAD

**Issue by parkerl** [exercism/xelm#10]
Not started

**Comment by tgecho** [comment]
I have a WIP here: https://github.com/tgecho/xelm/commit/d8278c98709080664b5d828c911c337e75ea06f7

I'm a bit concerned about requiring someone to dive into `Result` in such an early exercise... but I'm an Elm newbie myself, so maybe it's not too bad? Assuming this test/example seems reasonably idiomatic, what do you think?
