### ISSUE TITLE
`elm-test` emits unexpected stack trace.

### ISSUE THREAD

**Issue by jottr** [exercism/xelm#100]
```
$ pwd
~/dev/exercism/elm/hello-world

$ npm install -g elm-test

$ elm-test HelloWorldTests.elm

Success! Compiled 1 module.
Successfully generated /var/folders/mv/dy0670cn3255t3fjlv5dwk1m0000gn/T/elm_test_116720-91005-5fq85q.m8bp22o6r.js
undefined:1929
			throw new Error(
			^

Error: You are giving module `Main` an argument in JavaScript.
This module does not take arguments though! You probably need to change the
initialization code to something like `Elm.Main.fullscreen()`
    at init (eval at <anonymous> (/usr/local/lib/node_modules/elm-test/bin/elm-test:86:37), <anonymous>:1929:10)
    at Object.eval [as callback] (eval at <anonymous> (/usr/local/lib/node_modules/elm-test/bin/elm-test:86:37), <anonymous>:1973:17)
    at step (eval at <anonymous> (/usr/local/lib/node_modules/elm-test/bin/elm-test:86:37), <anonymous>:2613:39)
    at Timeout.work [as _onTimeout] (eval at <anonymous> (/usr/local/lib/node_modules/elm-test/bin/elm-test:86:37), <anonymous>:2671:15)
    at tryOnTimeout (timers.js:228:11)
    at Timer.listOnTimeout (timers.js:202:5)

```

I'm not sure where to go from here...
I recall that the exercises came with a `.bat`/`.sh`-script. Why have they been removed? 

Also, `elm-package.json` defines ` "rtfeldman/node-test-runner"` as a dependency.  But I still need to `$ npm install -g elm-test` to have `elm-test` available as a command.  
Is there a means to make locally installed binaries available within the project dir (i.e. `elm-test`)?

**Comment by kytrinyx** [comment]
> Is there a means to make locally installed binaries available within the project dir (i.e. elm-test)?

We're actively working on that.

@exercism/elm do you know if it would work to stick stuff in the root directory?

**Comment by tgecho** [comment]
I'm afraid some of our recent test dependency upgrades (https://github.com/exercism/xelm/issues/95) may have been done in a very graceful/backwards compatible way. In the process, we removed the runtests.sh/.bat scripts in favor of using the `elm-test` cli (https://github.com/exercism/xelm/issues/76).

These changes shouldn't require any change in how your solution is written, however you wouldn't have a good way to know that the documentation has changed. That's our bad.

I think in the sort term I might put the runtests scripts back to reduce confusion. Ideally we wouldn't need to make these sorts of changes, but I'm at a loss as to how to communicate them short of something like adding a "STUFF CHANGED!" comment to the empty solution file.

**Comment by kytrinyx** [comment]
> I think in the sort term I might put the runtests scripts back to reduce confusion.

How about sticking the runtests scripts back, but when you run them it echos to go look at the documentation?

> I'm at a loss as to how to communicate [these sorts of changes]

Yeah, me too. If our dashboard was better, we could put important notifications there,  but right now the dashboard is enough of a mess that I don't know that people would see it.

**Comment by tgecho** [comment]
> How about sticking the runtests scripts back, but when you run them it echos to go look at the documentation?

Of course! This is much better than the half baked backwards compatible thing I was trying to whip up.

> > I'm at a loss as to how to communicate [these sorts of changes]

> Yeah, me too.

I've had a few thoughts about what this sort of thing might look like. I'll try to crystalize them a bit and write them up somewhere.

**Comment by cjmochrie** [comment]
Maybe I'm missing something, but I've looked at the Elm documentation linked to in PR#01 and following those instructions I'm still getting the stack trace mentioned in the first post.

Is the problem that the existing problems' *Test.elm files will not work with `elm-test`? Sorry, frustrating to get stuck getting HelloWorld to work... Is there a possible workaround?

**Comment by lpil** [comment]
Hiya

Even with all the deps installed as instructed in the documentation this error still persists. There is something currently wrong with the test setup that is unrelated to the scripts used to run the elm test bin.

**Comment by jehoshua02** [comment]
Same issue here.

```
~/exercism/elm/say
$ node --version
v4.2.1
~/exercism/elm/say
$ elm --version
0.17.1
~/exercism/elm/say
$ elm-test --version
0.17.3
~/exercism/elm/say
$ elm-test SayTests.elm 
Success! Compiled 1 module.                                         
Successfully generated /var/folders/1p/qm72h6016651chtkxqygy7_w0000gn/T/elm_test_116721-44584-5r55tr.js
undefined:1929
			throw new Error(
			^

Error: You are giving module `Main` an argument in JavaScript.
This module does not take arguments though! You probably need to change the
initialization code to something like `Elm.Main.fullscreen()`
    at init (eval at <anonymous> (/Users/jstoutenburg/.nvm/versions/node/v4.2.1/lib/node_modules/elm-test/bin/elm-test:86:37), <anonymous>:1929:10)
    at Object.eval [as callback] (eval at <anonymous> (/Users/jstoutenburg/.nvm/versions/node/v4.2.1/lib/node_modules/elm-test/bin/elm-test:86:37), <anonymous>:1973:17)
    at step (eval at <anonymous> (/Users/jstoutenburg/.nvm/versions/node/v4.2.1/lib/node_modules/elm-test/bin/elm-test:86:37), <anonymous>:2613:39)
    at work [as _onTimeout] (eval at <anonymous> (/Users/jstoutenburg/.nvm/versions/node/v4.2.1/lib/node_modules/elm-test/bin/elm-test:86:37), <anonymous>:2671:15)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by jehoshua02** [comment]
Relevant: https://github.com/rtfeldman/node-test-runner/issues/62

**Comment by jehoshua02** [comment]
```
~/exercism/elm/say
$ elm-test SayTests.elm 
Success! Compiled 1 module.                                         
Successfully generated /var/folders/1p/qm72h6016651chtkxqygy7_w0000gn/T/elm_test_116721-44783-1v0yvok.js

elm-test
--------

Running 17 tests. To reproduce these results, run: elm-test --seed 1611331912


TEST RUN PASSED

Duration: 27 ms
Passed:   17
Failed:   0

```

**Comment by jehoshua02** [comment]
Okay, so here's what I had to change:

__elm-package.json__
```
        "rtfeldman/node-test-runner": "2.0.0 <= v < 3.0.0"
```

*Tests.elm
```
main : Program Value
main =
    run emit tests
```

**Comment by jehoshua02** [comment]
@kytrinyx @tgecho 

Do you see any problems with this solution?

1. update every repo elm-package.json to require node-test-runner 2
2. and update test file to `Program Value` instead of `Program Never`

If not, that's easy enough I'd be happy to sweep through the exercises and submit a pull request.

**Comment by kytrinyx** [comment]
:heart: thank you @jehoshua02 for figuring that out.
