### ISSUE TITLE
Downloaded exercises do not contain instructions on how to run tests

### ISSUE THREAD

**Issue by lpil** [exercism/xelm#104]
I just fetched the anagram exercise, and it did not contain instructions on how to run the tests. Here's the contents of the README as as I received it.

```
# Anagram

Write a program that, given a word and a list of possible anagrams, selects the correct sublist.

Given `"listen"` and a list of candidates like `"enlists" "google"
"inlets" "banana"` the program should return a list containing
`"inlets"`.

## Source

Inspired by the Extreme Startup game [https://github.com/rchatley/extreme_startup](https://github.com/rchatley/extreme_startup)

## Submitting Incomplete Problems
It's possible to submit an incomplete solution so you can see how others have completed the exercise.
```

**Comment by tgecho** [comment]
These readme files are generic across language tracks, so I don't think there's much we can do here. I wouldn't be opposed to embedding a quick boilerplate summary of the instructions as a comment in the stub file. This would probably make it safe to finish ditching the runtests files

**Comment by lpil** [comment]
That's not true, the READMEs for other exercises in other languages include instructions on running the tests. He's the same exercise from the Rust track.

```
# Anagram

Write a program that, given a word and a list of possible anagrams, selects the
correct sublist.

Given `"listen"` and a list of candidates like `"enlists" "google"
"inlets" "banana"` the program should return a list containing
`"inlets"`.

## Rust Installation

Refer to the exercism help page at
http://help.exercism.io/getting-started-with-rust.html for Rust installation
and learning resources.

## Writing the Code

Execute the tests with:

```bash
$ cargo test
```

All but the first test have been ignored.  After you get the first test to
pass, remove the ignore flag (`#[ignore]`) from the next test and get the tests
to pass again.  The test file is located in the `tests` directory.   You can
also remove the ignore flag from all the tests to get them to run all at once
if you wish.

Make sure to read the
[Crates and Modules](http://doc.rust-lang.org/stable/book/crates-and-modules.html)
chapter if you haven't already, it will help you with organizing your files.

## Source

Inspired by the Extreme Startup game
[view source](https://github.com/rchatley/extreme_startup)
```

**Comment by tgecho** [comment]
Huh... you're absolutely right. It turns out we totally missed the boat on customizing `SETUP.md`, which is the file that apparently gets appended. Looks like we'll need to fix that.

**Comment by lpil** [comment]
Great, thanks @tgecho

**Comment by jehoshua02** [comment]
@tgecho is this sufficient?

https://github.com/exercism/xelm/pull/112

**Comment by tgecho** [comment]
@jehoshua02 I think it's a good start. I could see adding slightly more info, but it certainly covers the basic need for now.
