### ISSUE TITLE
Unclear how to get/run 'elm-test'

### ISSUE THREAD

**Issue by i-s-o-g-r-a-m** [exercism/xelm#109]
On the elm track, the 'Hello, World' exercise has a shell script that runs tests via `elm-make`. So far so good. 

Then with 'Bob', you try the same thing to run the tests and you are referred to the 'Running the Tests' directions. Those say to run `elm-test *Test.elm`. I installed Elm in the way recommended on their website, but I don't have an `elm-test` anywhere. Looks like it is a third-party package that needs to be installed. Maybe we can indicate that and explain how to do it? Let me know if I can provide some text.

Thanks -- exercism is awesome!

**Comment by tgecho** [comment]
Yes, this is a bit confusing. We have a note in the track level docs (https://github.com/exercism/xelm/blob/master/docs/INSTALLATION.md), but nothing that ships with the exercise itself. Fixing https://github.com/exercism/xelm/issues/104 should help with this.

**Comment by tgecho** [comment]
The minimum info required (a link to the larger instructions) was added as part of #112. We might flesh it out a bit more, but this is a good start.

**Comment by i-s-o-g-r-a-m** [comment]
@tgecho thanks!
