### ISSUE TITLE
request for help

### ISSUE THREAD

**Issue by rebelwarrior** [exercism/xelm#132]
I want to design a new exercise that calculates the amount of seconds from the Sept 1 1970 moment till present, this would require getting the "date.now" functionality from JS through a port. And I've not idea how to design that. Anybody want to help?

**Comment by tgecho** [comment]
There is actually already an Elm equivalent in the Time.now task (http://package.elm-lang.org/packages/elm-lang/core/latest/Time#now).

Unfortunately I'm not sure of the best way to incorporate such an Elm specific exercise.

**Comment by tgecho** [comment]
... didn't mean to post that quite yet, but I'll continue. :)

Adding the current time as a factor in unit tests makes them quite a bit messier (I'm not sure elm-test) even has provision for incorporation ports/subscriptions/etc. Usually you'd write unit tests against hard coded Time values so that your expected results can also be specified explicitly. 

All that is to say that I'm not sure, but I suspect more advanced and Elm specific exercises probably need a home outside of Exercism :)

**Comment by rebelwarrior** [comment]
That (elm) function is a subscription if I understand it right and doesn't run like say Date.now in JS (which would be the one you'd use).
In a web app you can call the JS function by using a port. It is not too hard to do (you have to create a port on the JS side and that's a bit of doing) but I don't know how to do that in a command line application. 
I know it can be done because elm-test does it.

**Comment by rebelwarrior** [comment]
It might make Elm-test messier true but on the point that exercism is not the place for it I'd challenge that. The exercise itself is not Elm specific just the solution. I'll check but I think other language tracks have the exact same exercise. Just implementing it in Elm is more complicated.

**Comment by tgecho** [comment]
That's correct, but in the end you'd have essentially the same thing: an incoming message from Elm's `Time.now` task or from a subscription to a port returning JS's `Date.now()`. I could be wrong, but I don't think elm-test has any way to incorporate these into a test suite.

I'm totally up for ideas! I'm not trying to say "no" (not really my call anyway ;) ), just that I'm not sure how it fits. I'd be curious to see if other tracks actually use the current date in their tests or if they simply hard code specific example tests.

**Comment by tgecho** [comment]
I'm sorry that I let this kinda fizzle out. I still think the most correct answer (from a general unit test perspective and an Exercism specific perspective) is to test a predefined set of dates.

I'm closing this to tidy things up. Please feel free to reopen if you want to go over anything else!
