### ISSUE TITLE
Tests broken with elm-test 0.18.3

### ISSUE THREAD

**Issue by PascalLeMerrer** [exercism/xelm#138]
I just fetched the "largest-series-product" exercise.
Like for all previous exercises, I executed in the project directory:
   
    npm install
    npm test

It fails :

    > @ test /Users/pascallemerrer/exercism/elm/largest-series-product
    > elm-test Tests.elm
    It looks like you're runing elm-test from within your tests directory
    Please run elm-test from your project's root directory, where its elm-package.json lives!

To fix it I replaced the node_modules directory with the one of the previous exercise.
It uses elm-test@0.18.2, while the last one downloaded elm-test@0.18.3

**Comment by PascalLeMerrer** [comment]
It's likely related to this [commit](https://github.com/rtfeldman/node-test-runner/commit/73e46a5d0bfd3e4839d11b380b1d3e94f29098af)

I see to ways to fix this:

- pin the version number for elm-test to 0.18.2, in package.json
- better: move Tests.elm to tests/Main.elm, and change `"test": "elm-test Tests.elm"` to `"test": "elm-test" in package.json

**Comment by PascalLeMerrer** [comment]
It' also broken by [issue#143](https://github.com/rtfeldman/node-test-runner/issues/143)
It's probably better to stick to release 0.18.2, until a fix is out.

**Comment by tgecho** [comment]
Thanks for the report! We're going to have all of the exercises updated to be compatible with the latest version of elm-test shortly (see #139). In addition, we'll be pinning to a specific version of our npm deps going forward to stop this from happening again.
