### ISSUE TITLE
*.example files

### ISSUE THREAD

**Issue by tgecho** [exercism/xelm#16]
Since things are still in an early state, does anyone have any objections to switching to `ExerciseExample.elm` as the example naming convention? I'm working on adding a few exercises and it's a bit tedious since editors don't really like the .example extension. Also, it would make it possible to dev on a test by simply changing the import line to `import BobExample exposing (hey)`.

Any thoughts/objections? @parkerl @kytrinyx

**Comment by parkerl** [comment]
Hey @tgecho, welcome to the party! I'm personally open to anything. Using `.example` was an easy way to get CI working and keeps the build script nice and simple. 

FWIW, my process has been to develop as normal with the regular `.elm` extension, like `HelloWorld.elm`. I don't use the build script for testing when working on an exercise but call `elm-test` directly with `elm-test exercises/hello_world/HelloWorldTests.elm`. When the exercise is green, the final steps are to change the extension, add the template file and run `bin/build.sh`. 

That has been working well for me.

**Comment by tgecho** [comment]
Yep... after doing a few more exercises (PRs incoming!) I care even less strongly about this. The only concrete reason I can come up with is if someone comes along and wants to view an example the syntax highlighting will be off.

On the other hand, technically a `BobExample.elm` file with `module Hamming (..) where` is invalid... so yeah, I don't care enough :)

**Comment by parkerl** [comment]
Ooooo PRs! Sweet! I'm glad things are working for you. :tada:

**Comment by parkerl** [comment]
@tgecho I am going to update the README a bit with this workflow. Hope that helps.
