### ISSUE TITLE
elm-reactor

### ISSUE THREAD

**Issue by tgecho** [exercism/xelm#18]
I'm not sure if it's a problem with how things are set up in this repo, my own installation or if it's related to the current ongoing issues with elm-reactor, but it doesn't seem to be working for me here at all.

![image](https://cloud.githubusercontent.com/assets/49615/13719732/36fb147c-e7c8-11e5-9b97-27af8b8ede07.png)

For reference, I have been able to use it with other projects, so it's not completely broken on my computer. Might it make sense to switch to `elm-test` as the recommended method for now?

@parkerl

**Comment by parkerl** [comment]
@tgecho yeah, the exercises I have built are testable at the command line with `elm-test`. I think `elm-console` is not going to work in the browser. Again, this was all just to get the project up and started with CI.

**Comment by tgecho** [comment]
Fixed by the merge of https://github.com/exercism/xelm/pull/29

**Comment by parkerl** [comment]
This is fixed now?

**Comment by tgecho** [comment]
Sorry, bad wording. elm-reactor isn't fixed, but the issue is addressed by switching away from it :)
