### ISSUE TITLE
Get the `docs` in order

### ISSUE THREAD

**Issue by parkerl** [exercism/xelm#23]
We need the following:

- [x] INSTALLATION.md - should contain details about installing the language itself and any dependencies or configuration necessary to work on the exercises in that language.
- [x] TESTS.md - about how to run the tests for the exercises.
- [x] ABOUT.md - a short, friendly blurb about the language. What types of problems does it solve really well? What is it typically used for?
- [x] LEARNING.md - a few notes about where people might want to go to learn the language from scratch.
- [x] RESOURCES.md - references and other useful resources.

per https://github.com/exercism/todo/issues/1

**Comment by parkerl** [comment]
@tgecho thanks for your help on these already. Here is the list of what is needed.

**Comment by tgecho** [comment]
So, I left a comment buried in a PR here https://github.com/exercism/xelm/pull/22#discussion_r55929561

I think the most important thing we need to do is sort out the learner install/test workflow. I think the contributor workflow isn't broken.

As far as I can tell the learner will receive any files without "example" in the name, so we could place an individual elm-package.json in each exercise directory with the elm-test/elm-console dependencies listed. A bit tedious, but a single copy and paste per exercise will save every learner a bit of annoyance.

There seems to be precedent for this sort of pattern:
https://github.com/exercism/xscala/blob/master/exercises/bob/build.sbt
https://github.com/exercism/xclojure/blob/master/exercises/bob/project.clj

If no one is opposed I'll throw up a PR updating all of the existing exercises and relevant documentation. Once we have that somewhat settled I'm eager to get the exercises I've been putting together merged in. We've got ten including hello-world!

**Comment by tgecho** [comment]
I'm not really sure what to put in learning vs resources. A few random prominent blog posts?

Maybe a link to exercise? :)

**Comment by kytrinyx** [comment]
[Did you mean recursion?](https://www.google.com/?q=recursion) :)

Learning is for things that are good when first picking up a language, resources is for things that you might use while developing on a daily basis (language docs, etc).

**Comment by tgecho** [comment]
Very nice. :)

I think we've got a decent start: https://github.com/exercism/xelm/pull/40
