### ISSUE TITLE
Upload Elm logo

### ISSUE THREAD

**Issue by tgecho** [exercism/xelm#45]
It looks like we'll want
- [ ] An "Exercism colorized" version of the Elm logo in [exercism.io/public/img/](https://github.com/exercism/exercism.io/tree/master/public/img) (~1024x1024?)
- [ ] Appropriate attribution to [exercism.io/ATTRIBUTION.md](https://github.com/exercism/exercism.io/blob/master/ATTRIBUTION.md)
- [ ] A style rule in [exercism.io/public/sass/base/components/main.scss](https://github.com/exercism/exercism.io/blob/master/public/sass/base/components/main.scss) (probably not needed?)

Official logo SVG: https://github.com/elm-lang/elm-lang.org/blob/master/resources/logo.svg

**Comment by kytrinyx** [comment]
Nice! Do you happen to know what the copyright situation is with the logo? If it's public domain or creative commons then there's a good chance I can make the change and reference it without asking anyone, but if not, then I'll want to ask the right people for permission to use it and change it.

**Comment by kytrinyx** [comment]
Also, I can't remember, but I think I don't use any of the logo styles in the CSS anymore. It was getting annoying to add those.

**Comment by kytrinyx** [comment]
One more thing: I have a script that I use to colorize the logos, so don't worry about that unless you actually know how to do it (I shaved a couple of yaks trying to figure it out).

**Comment by kytrinyx** [comment]
Oh, please make the logo small-ish. Also, I just moved all the track icons to `/public/img/tracks/` https://github.com/exercism/exercism.io/tree/master/public/img/tracks

**Comment by tgecho** [comment]
I looked around a bit more for copyright info, but ended up pinging the mailing list. I also found an .svg in the elm-lang.org repo.

**Comment by parkerl** [comment]
@tgecho any word on the logo? I think that is the only thing holding us up from a "real" release right @kytrinyx ?

**Comment by tgecho** [comment]
Nope. I've emailed the mailing list as well as Evan directly with no response. I doubt anyone would complain if we put a "fair use" attribution up, but I don't know where @kytrinyx's threshold lies.

**Comment by kytrinyx** [comment]
I think that we're good under fair use, except in certain cases where the company that owns the language has put extremely tight restrictions on the use of the logo (**cough** Java **cough**).

If someone does get back to us later and asks us to remove or tweak the icon we're using, we can always do so then.

**Comment by kytrinyx** [comment]
I don't have anything that handles SVGs (If someone does, then I would love to redo all of the icons on the site as SVG. PNG is just because I suck at graphics). I took a screenshot of the logo and am proceeding to mangle it. I'll upload a suggestion for the exercism-colored icon.

**Comment by kytrinyx** [comment]
![elm](https://cloud.githubusercontent.com/assets/276834/14325166/47113b80-fbe5-11e5-9a4c-f975add115a6.png)

Thoughts?

**Comment by parkerl** [comment]
Looks good to me!

**Comment by kytrinyx** [comment]
OK, I'm adding this and deploying it.

**Comment by kytrinyx** [comment]
OK, here we go: https://github.com/exercism/exercism.io/commit/a618e2d8f7c914255af0200df3aadbf5d498d714
![screen shot 2016-04-06 at 11 11 53](https://cloud.githubusercontent.com/assets/276834/14325841/6723c372-fbe8-11e5-8026-db38e367f1e5.png)
