### ISSUE TITLE
Run elm-format on CI

### ISSUE THREAD

**Issue by parkerl** [exercism/xelm#47]
Because we are being strict about formatting we should fail the build if elm-format causes diffs.

**Comment by justgage** [comment]
I would be a little afraid that this would cause people to become a little discouraged. I think suggesting to use it with a bot in a comment after they submit it could be a good thing.

**Comment by kytrinyx** [comment]
@justgage To clarify this about pull requests on GitHub to the Exercism Elm track, not about failing the tests when people are submitting exercises to the website.

**Comment by justgage** [comment]
Ah yes, that's a good idea. Sorry about that.

**Comment by kytrinyx** [comment]
No apologies necessary—you've got everyone's best interest in mind (and I agree with you: this would be frustrating and potentially quite discouraging if we did it on the website).
