### ISSUE TITLE
Test suites aren't showing up on exercism.io

### ISSUE THREAD

**Issue by tgecho** [exercism/xelm#48]
The exercise pages have a "Test Suite" tab, but it seems to be broken for the Elm exercises.

For example...
The Python test suite: http://exercism.io/exercises/python/hello-world
The Elm version is broken: http://exercism.io/exercises/elm/hello-world

Is there something we can/should tweak to fix this?

**Comment by kytrinyx** [comment]
Yeah, this has to do with the `test_pattern` in the `config.json`. If you delete the `test_pattern` key the test suites should show up (since they have `[Tt]est` in the name).
