### ISSUE TITLE
elm-test doesn't work

### ISSUE THREAD

**Issue by CoderDennis** [exercism/xelm#58]
I'm getting started with Elm exercises and am a complete newbie with Elm. Following the instructions, when I enter `elm-test HelloWorldTests.elm` I get `Could not find Elm compiler "elm-make". Is it installed?`

I can run `elm make HelloWorldTests.elm` successfully (it generates an `index.html` file), so I think that means `elm-make` is installed.

I'm on Windows if that makes a difference. I installed via `npm install --global elm elm-test`

**Comment by tgecho** [comment]
Ah! I'm afraid I haven't tested things on Windows. I'll try to check it out this evening.

**Comment by tgecho** [comment]
I just ran through the instructions in a Windows 8 VM with Node 5.x and everything seems to work. What version of Windows and Node/npm are you using?

**Comment by CoderDennis** [comment]
I'm on my Windows 10 laptop (node v0.12.2) and it's working now! The error is on a Win 8.1 VM with Node v5.0.0. My laptop is primary machine, so it's not a big deal for that VM.

**Comment by rebelwarrior** [comment]
It would be good to post the solution. 
BTW using a mac I was running the exercises fine until I decided to install `npm -g install elm-test` it was slower than the previous one so I uninstalled it and the command disappeared....

**Comment by CoderDennis** [comment]
@rebelwarrior are you saying you got the same error?

I never found the solution. I just didn't care to pursue it any further since it seemed to be isolated to a machine that I wasn't going to use any more.

**Comment by rebelwarrior** [comment]
I did not get the same error. I got something else. I was unable to diagnose so just had to reinstall NPM -g install elm-test.
