### ISSUE TITLE
Misleading type in the Triangle for Elm exercise readme.

### ISSUE THREAD

**Issue by RiderSargent** [exercism/xelm#66]
In the Triangle exercise readme (http://exercism.io/exercises/elm/triangle/readme), it says 

    "Tests are provided, delete one `skip` at a time."

But there are no skipped tests. I'm happy to fix it, but I couldn't find the readme in this repo or the `exercism.io` repo. Can anyone point me in the right direction?

And thanks for all the work bringing Elm to Exercism! I'm loving the exercises.

**Comment by tgecho** [comment]
Whoops, that is a bit confusing. Unfortunately, the exercise readme is shared between all of the language tracks (specifically here in the x-common repo: https://github.com/exercism/x-common/blob/master/triangle.md. In this case it may be a bit too specific, but I missed that part when I set up the tests. We can either submit a PR for the readme or figure out a way to add skips to these elm tests.

I'm not in a place to do either at the moment, so you're welcome to take a shot at it.

**Comment by tgecho** [comment]
Upstream readme has been updated. Thanks!
