### ISSUE TITLE
Upgrade exercises to Elm 0.17

### ISSUE THREAD

**Issue by tgecho** [exercism/xelm#74]
The only real code change that should be necessary is updating the module lines from `module Main (..) where` to `module Main exposing (..)` form. We're not doing any signal stuff yet, so the rest of the upgrade doc shouldn't affect us: https://github.com/elm-lang/elm-platform/blob/master/upgrade-docs/0.17.md

It also looks like we may need to switch to `elm-community/elm-test` to gain 0.17 support. I'm traveling with sketchy internet access at the moment, so I won't be able to sort this out in the next day or two.

**Comment by despairblue** [comment]
Also we'd have to wait for elm-console to be upgraded to elm@0.17.

I'm happy to adapt the exercises while working through them. I just might need some guidance from time to time. At the moment I'm still struggling to get the testing to work, but I guess I have to wait for elm-console.

**Comment by lukewestby** [comment]
Hello! I'm here to help with this! Having xelm upgraded to 0.17 has suddenly become a pressing need. So elm-community/elm-test no longer relies on elm-console, it can just be compiled and run in node. I can submit a PR or help y'all get things working some time in the next couple days. Let me know!

**Comment by despairblue** [comment]
@lukewestby So I assume the [readme](https://github.com/elm-community/elm-test#testing-from-the-command-line) is out of date? 

> There is one more version of this function: consoleRunner : Test -> IO (). This is designed to work with Laszlo Pandy's elm-console library. See the below section on Testing from the Command Line for details.

**Comment by lukewestby** [comment]
Yep, the README wasn't updated with the changes. Now if you want to run in the console you use

```elm
main : Program Never
main =
    ElmTest.runSuite tests
```

and it will make use of `Debug.log` and `Debug.crash` internally to report to the console and crash the process on test failure.

**Comment by tgecho** [comment]
Yeah, I figured that much out (see PR #75).

Now we're mostly waiting to see if/when node-elm-test will be updated so we can keep the same workflow.

We also need to tweak the sublist example.

**Comment by Swizz** [comment]
Hi guys.

I have this issue since the last change :

> Could not find package elm-lang/core.
>
>Maybe your elm-stuff/ directory has been corrupted? You can usually fix stuff
> like this by deleting elm-stuff/ and rebuilding your project.

I tried to remove the `elm-stuff/` and the `~/.elm` folders but nothing works.

Regards,

**Comment by despairblue** [comment]
Can you try to delete the elm-package.json and refetch the excercise.

On Wed, May 18, 2016, 13:34 Quentin Gerodel <notifications@github.com>
wrote:

> Hi guys.
>
> I have this issue since the last change :
>
> Could not find package elm-lang/core.
>
> Maybe your elm-stuff/ directory has been corrupted? You can usually fix
> stuff
> like this by deleting elm-stuff/ and rebuilding your project.
>
> I tried to remove the elm-stuff/ and the ~/.elm folders but nothing works.
>
> Regards,
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/exercism/xelm/issues/74#issuecomment-220000228>
>
-- 
Q: Why is this email five sentences or less?
A: http://five.sentenc.es

**Comment by Swizz** [comment]
This does not work.

I will try to reinstall all my elm environnent.
