### ISSUE TITLE
runtests.sh is not downloaded with executable permissions

### ISSUE THREAD

**Issue by tgecho** [exercism/xelm#76]
```
$ ./runtests.sh
-bash: ./runtests.sh: Permission denied
```

I didn't even think to check/ask, but it looks like this behavior was changed a few months ago: https://github.com/exercism/cli/issues/276 :(

So... seeing as in my haste I've failed to create a clean/generic wrapper on the first try, I see a few obvious options:

1. Remove the wrappers, switch the instructions back and wait for an updated `elm-test` to ship. `elm-test MyTests.elm` actually works right now, it just has a bunch of extraneous garbage at the end of the output.
2. Update the instructions to `bash runtests.sh`.
3. Write a node.js based wrapper (which could actually be cross platform) and instruct them to run `node runtests.js`.

Thoughts @parkerl @lukewestby?

**Comment by jwithington** [comment]
Also: if you're like me, you ended up here wondering why you couldn't run the tests.

This link helped me understand chown enough to get them running.

https://help.ubuntu.com/community/FilePermissions

**Comment by Calvyn82** [comment]
I'm willing to sit down this weekend and update the README for this track to walk newbies through how to make the .sh files executables for Linux and Mac users. I'm not sure what the appropriate way to describe running a .bat file in windows. Enter the filename from a cmd prompt?

**Comment by tgecho** [comment]
@Calvyn82 thanks for reminding me about this! I'm really unhappy with asking people to modify the runtests scripts every time they download a new exercise.

I'm almost tempted to switch back to recommending `elm-test-runner`, with the caveat that it shows an odd error message at the end. It does look like rtfeldman is planning to update soon: https://github.com/rtfeldman/node-test-runner

```sh
$ elm-test SayTests.elm
Success! Compiled 1 module.
Successfully generated /var/folders/c8/lwxn19p55rj7mq0n7xhj0hv00000gp/T/elm_test_116615-34499-1gpd4jn.js
Successfully compiled SayTests.elm
Running tests...
  1 suites run, containing 17 tests
  All tests passed


: ""

[stdin]:7603
    if (typeof Elm === "undefined") { throw "elm-io config error: Elm is not defined. Make sure you call elm-io with a real Elm output file"}
                                      ^
elm-io config error: Elm is not defined. Make sure you call elm-io with a real Elm output file
```

If we want to stay self sufficient, I think I'd prefer to write a little node powered wrapper. Thoughts?
