### ISSUE TITLE
Is it possible to write tests for html?

### ISSUE THREAD

**Issue by rebelwarrior** [exercism/xelm#89]
One of the features of Elm I really like is all its front end magic, but I don't know how to write tests for that. I don't know if they are even possible (without say Selenium)?

**Comment by tgecho** [comment]
This is a really good question. I'd love some ideas about how to sprinkle in some of the more advanced aspects of Elm such as html rendering, but I'm not really sure how that best fits into Exercism. The existing exercises are pretty much generic, and I don't know how good the support is for doing custom language specific exercises.

**Comment by rebelwarrior** [comment]
There are language specific tests (there is one for Haskell Lenses, whatever that is). 
The question is can a command line test be done without adding external dependencies?

**Comment by tgecho** [comment]
Oh, well then that's a great precedent. I'm personally not opposed to (carefully chosen) pure Elm dependencies, as long as we can add them to the `elm-package.json` and have them automatically download like the rest.

**Comment by tgecho** [comment]
I'm closing this as not specifically actionable (please feel free to reopen if you disagree). I'd personally support any efforts to bring new types of tests that show off more of Elm.
