### ISSUE TITLE
ListOps: Direction tests for foldl and foldr

### ISSUE THREAD

**Issue by arnau** [exercism/xelm#93]
Hi, I just did the ListOps exercise and I missed one test to cover the difference between `foldl` and `foldr`.  Something on the lines of

```elm
, test "direction" (assertEqual [4,3,2,1] (foldl (::) [] [1..4]))
```

and

```elm
, test "direction" (assertEqual [1..4] (foldr (::) [] [1..4]))
```

What do you think?

**Comment by tgecho** [comment]
Yeah, that's a great point. I won't be able to squeeze it in until the weekend, but I'll happily merge a PR.

**Comment by tgecho** [comment]
Thanks! :tada:
