### ISSUE TITLE
Update to use the latest version of Elm Test

### ISSUE THREAD

**Issue by lpil** [exercism/xelm#95]
Hello!

Currently the Elm exercises are using an older version of Elm Test that is unmaintained and uses ugly hacks to report tests results to the user.
I believe we should update to use the latest version.

There are a few problems with this:
- The current version has a new syntax for tests that we would need to update to.
- Due to the nature of Elm there isn't an obvious way to do IO, so there are multiple solutions for returning test results to the user. We would need to decide how to run out tests in a fashion that is user friendly and does not pull too many dependencies into the exercises.

**Comment by tgecho** [comment]
I totally agree that we should sort this out. I was hoping to take a stab at solving https://github.com/exercism/xelm/issues/76 while we're at it.

**Comment by tgecho** [comment]
First example exercise upgrade: https://github.com/exercism/xelm/pull/96

I'm going to work on porting the rest of the exercises. What do you think @lpil?

**Comment by lpil** [comment]
:tada:
